import time
nome1 = str(input("Digite o nome 1:"))
nome2 = str(input("Digite o nome 2:"))
nome3 = str(input("Digite o nome 3:"))
time.sleep (0.7)
print(nome1)
time.sleep (5.0)
print(nome2)
time.sleep (5.0)
print(nome3)